# Generated by Django 5.0.7 on 2024-07-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
